name: Kör tester

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hämta repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Installera pytest
        run: pip install -r requirements.txt

      - name: Kör tester
        run: pytest
